version: '3.8'

services:
  # -------------------
  # Meilisearch
  # -------------------
  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: meilisearch
    environment:
      - MEILI_MASTER_KEY=Jacare2603!
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    restart: unless-stopped

  # -------------------
  # Redis
  # -------------------
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # -------------------
  # MinIO (S3 compatível)
  # -------------------
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001" # Console web
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  meili_data:
  redis_data:
  minio_data:
