name: Laravel CI/CD

on:
  push:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: adivinheganhe_test
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      meilisearch:
        image: getmeili/meilisearch:v1.11
        ports:
          - 7700:7700
        options: >-
          --health-cmd="curl -s http://localhost:7700/health | grep available"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          MEILI_MASTER_KEY: masterKey123

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, intl, pdo_mysql

      - name: Copy .env
        run: cp .env.example.testing .env

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Generate key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --seed

      - name: Reindex users in Meilisearch
        run: php artisan scout:import "App\Models\User"

      - name: Run tests
        run: php artisan test

  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Deploy to server 2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH2_HOST }}
          username: ${{ secrets.SSH2_USER }}
          key: ${{ secrets.SSH2_KEY }}
          script: |
            cd /var/www/adivinheganhe
            rm composer.lock
            git stash
            git pull origin master
            composer install --optimize-autoloader --prefer-dist
            php artisan migrate --force
            php artisan route:cache
            php artisan view:clear
            php artisan cache:clear
            systemctl restart octane
            php artisan scout:index users
            php artisan scout:queue-import "App\Models\User"
